### ISSUE TITLE
Automatic renaming of python-boilerplate to project name

### ISSUE THREAD

**Issue by GoldraK** [pmareke/python-boilerplate#3]
I don't know how the best way would be, but some type of script in bash and ps1 could be proposed that substitutes the name python-boilerplate to the name of the project that is going to be created to normalize it automatically.

Thanks for your work

**Comment by pmareke** [comment]
Thanks for the feedback! You can always run in your IDE and Find and Replace, right?

**Comment by GoldraK** [comment]
Thanks for your work.
